version: 2.1
orbs:
  node: circleci/node@1.1.6

references:
  set_environment_variables: &set_environment_variables
    run:
      name: Set Environment Variables
      command: |
        echo 'export ES_LINT_SOURCE=./webapp/src/**/**/**/**.ts' >> ${BASH_ENV}
  
  restore_deps: &restore_deps
    restore_cache:
      keys:
        - v2-dependencies-{{ checksum "webapp/package.json" }}
jobs:
  install-deps:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - save_cache:
          paths:
            - node_modules
            - webapp/node_modules
          key: v2-dependencies-{{ checksum "webapp/package.json" }}
  unit-test:
    docker:
      - image: circleci/node:12-browsers-legacy
    steps:
      - checkout
      - checkout
      - <<: *restore_deps
      - <<: *set_environment_variables
      - run:
          name: Unit Test
          command: |
            ls -la
            ls -la webapp/
            npm run test
  linting-js:
    docker:
      - image: circleci/node:12-browsers-legacy
    steps:
      - checkout
      - <<: *restore_deps
      - <<: *set_environment_variables
      - run:
          name: "Lint Test"
          command: |
            ls
            pwd
            mkdir -p test-results/es_lint
            ./node_modules/.bin/eslint $ES_LINT_SOURCE > test-results/es_lint/eslint-results.json
      - store_artifacts:
          path: test-results/es_lint


workflows:
    project-homefront:
      jobs:
        - install-deps
        - linting-js:
            requires:
              - install-deps
        - unit-test:
            requires:
              - install-deps